environment:
  MYSQL_DATABASE: node_mysql 
  MYSQL_HOST: localhost
  MYSQL_USER: root 
  MYSQL_PASSWORD: Password12!  
  MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 5.7 
  MYSQL_PORT: 3306

  matrix:
    - nodejs_version: "0.8"
    - nodejs_version: "0.10" 
    - nodejs_version: "0.12"
    - nodejs_version: "1.8"
    - nodejs_version: "2.5"
    - nodejs_version: "3.3"
    - nodejs_version: "4.9"
    - nodejs_version: "5.12"
    - nodejs_version: "6.17"
    - nodejs_version: "7.10"
    - nodejs_version: "8.17"
    - nodejs_version: "9.11"
    - nodejs_version: "10.21"
    - nodejs_version: "11.15"
    - nodejs_version: 
 
